// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkqRjTHDW5iiWcFLV6YeXN2lNyRR9D-CU',
    appId: '1:525336553036:web:4b2ebc567f35f10be576e9',
    messagingSenderId: '525336553036',
    projectId: 'aplikacja-sportowa-ac07c',
    authDomain: 'aplikacja-sportowa-ac07c.firebaseapp.com',
    databaseURL: 'https://aplikacja-sportowa-ac07c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aplikacja-sportowa-ac07c.appspot.com',
    measurementId: 'G-Z30QSP4JGG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDjjJkmkHWF_CJanf4QTiMKY_0pCgmiUyI',
    appId: '1:525336553036:android:614bead43c8c7efae576e9',
    messagingSenderId: '525336553036',
    projectId: 'aplikacja-sportowa-ac07c',
    databaseURL: 'https://aplikacja-sportowa-ac07c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aplikacja-sportowa-ac07c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdI6kipOCLO3BKPKjgCNKU36s1mXX1mAo',
    appId: '1:525336553036:ios:f2609e430279ad9ce576e9',
    messagingSenderId: '525336553036',
    projectId: 'aplikacja-sportowa-ac07c',
    databaseURL: 'https://aplikacja-sportowa-ac07c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aplikacja-sportowa-ac07c.appspot.com',
    iosClientId: '525336553036-eec57ggrgt7tgkecphqln91gu5ahm24r.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikacjaSportowa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdI6kipOCLO3BKPKjgCNKU36s1mXX1mAo',
    appId: '1:525336553036:ios:6b2c339c1a3e4aa4e576e9',
    messagingSenderId: '525336553036',
    projectId: 'aplikacja-sportowa-ac07c',
    databaseURL: 'https://aplikacja-sportowa-ac07c-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'aplikacja-sportowa-ac07c.appspot.com',
    iosClientId: '525336553036-v9817h3s34c682plhs0801d5tdmgf3vk.apps.googleusercontent.com',
    iosBundleId: 'com.example.aplikacjaSportowa.RunnerTests',
  );
}
